### ISSUE TITLE
zip file

### ISSUE THREAD

**Issue by BarlaanArynne** [BarlaanArynne/BSIT-WMA-4C-IPT2#3]
Send a zip file of the contents of your portfolio. Just attach it in a comment. ty.

**Comment by HalimawMamulutan** [comment]
Ayaw malagay "File size too big: 25 MB are allowed, 70 MB were attempted to upload." daw huhu

**Comment by HalimawMamulutan** [comment]
I-send ko na lang via teams

**Comment by BarlaanArynne** [comment]
ok thank you.
